var searchData=
[
  ['change_20log_0',['Change log',['../md__c__workspace__proyecto__p_h_p_project_vendor_php_di_php_di_change_log.html',1,'']]],
  ['change_20log_1',['Change Log',['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_php_file_iterator__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_code_unit_reverse_lookup__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_object_enumerator__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_object_reflector__change_log.html',1,'(Global Namespace)']]],
  ['changelog_2',['Changelog',['../md__c__workspace__proyecto__p_h_p_project_vendor_fig_http_message_util__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_jangregor_phpstan_prophecy__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_phar_io_manifest__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_phar_io_version__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)']]],
  ['changelog_3',['ChangeLog',['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_php_code_coverage__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_php_invoker__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_php_text_template__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_php_timer__change_log.html',1,'(Global Namespace)']]],
  ['changelog_4',['Changelog',['../md__c__workspace__proyecto__p_h_p_project_vendor_psr_http_message__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['changelog_5',['ChangeLog',['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_cli_parser__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_code_unit__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_comparator__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_complexity__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_diff__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_exporter__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_lines_of_code__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_recursion_context__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_resource_operations__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_type__change_log.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_version__change_log.html',1,'(Global Namespace)']]],
  ['changelog_6',['Changelog',['../md__c__workspace__proyecto__p_h_p_project_vendor_slim_slim__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_theseer_tokenizer__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_webmozart_assert__c_h_a_n_g_e_l_o_g.html',1,'(Global Namespace)']]],
  ['changes_20in_20phpunit_208_2e5_7',['Changes in PHPUnit 8.5',['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_phpunit__change_log_8_5.html',1,'']]],
  ['changes_20in_20phpunit_209_2e5_8',['Changes in PHPUnit 9.5',['../md__c__workspace__proyecto__p_h_p_project_vendor_phpunit_phpunit__change_log_9_5.html',1,'']]],
  ['changes_20in_20sebastian_2fglobal_2dstate_9',['Changes in sebastian/global-state',['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_global_state__change_log.html',1,'']]],
  ['changes_20in_20sebastianbergmann_2fenvironment_10',['Changes in sebastianbergmann/environment',['../md__c__workspace__proyecto__p_h_p_project_vendor_sebastian_environment__change_log.html',1,'']]],
  ['container_20interface_11',['Container interface',['../md__c__workspace__proyecto__p_h_p_project_vendor_psr_container__r_e_a_d_m_e.html',1,'']]],
  ['contributing_12',['Contributing',['../md__c__workspace__proyecto__p_h_p_project_vendor_doctrine_instantiator__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_php_di_invoker__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'(Global Namespace)'],['../md__c__workspace__proyecto__p_h_p_project_vendor_squizlabs_php_codesniffer__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'(Global Namespace)']]]
];
