var _arbitrary_parentheses_spacing_unit_test_8php =
[
    [ "ArbitraryParenthesesSpacingUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_white_space_1_1_arbitrary_parentheses_spacing_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_white_space_1_1_arbitrary_parentheses_spacing_unit_test" ]
];