var _assignment_in_condition_unit_test_8php =
[
    [ "AssignmentInConditionUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_code_analysis_1_1_assignment_in_condition_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_code_analysis_1_1_assignment_in_condition_unit_test" ]
];