var _boolean_operator_placement_sniff_8php =
[
    [ "BooleanOperatorPlacementSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_control_structures_1_1_boolean_operator_placement_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_control_structures_1_1_boolean_operator_placement_sniff" ]
];