var _browser_specific_styles_unit_test_8php =
[
    [ "BrowserSpecificStylesUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_c_s_s_1_1_browser_specific_styles_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_c_s_s_1_1_browser_specific_styles_unit_test" ]
];