var _call_time_pass_by_reference_sniff_8php =
[
    [ "CallTimePassByReferenceSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_functions_1_1_call_time_pass_by_reference_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_functions_1_1_call_time_pass_by_reference_sniff" ]
];