var _camel_caps_function_name_sniff_8php =
[
    [ "CamelCapsFunctionNameSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_naming_conventions_1_1_camel_caps_function_name_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_naming_conventions_1_1_camel_caps_function_name_sniff" ]
];