var _camel_caps_method_name_unit_test_8php =
[
    [ "CamelCapsMethodNameUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r1_1_1_tests_1_1_methods_1_1_camel_caps_method_name_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r1_1_1_tests_1_1_methods_1_1_camel_caps_method_name_unit_test" ]
];