var _character_before_p_h_p_opening_tag_unit_test_8php =
[
    [ "CharacterBeforePHPOpeningTagUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_p_h_p_1_1_character_before_p_h_p_opening_tag_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_p_h_p_1_1_character_before_p_h_p_opening_tag_unit_test" ]
];