var _character_before_p_h_p_opening_tag_sniff_8php =
[
    [ "CharacterBeforePHPOpeningTagSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_p_h_p_1_1_character_before_p_h_p_opening_tag_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_p_h_p_1_1_character_before_p_h_p_opening_tag_sniff" ]
];