var _class_definition_closing_brace_space_unit_test_8php =
[
    [ "ClassDefinitionClosingBraceSpaceUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_c_s_s_1_1_class_definition_closing_brace_space_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_c_s_s_1_1_class_definition_closing_brace_space_unit_test" ]
];