var _class_definition_closing_brace_space_sniff_8php =
[
    [ "ClassDefinitionClosingBraceSpaceSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_c_s_s_1_1_class_definition_closing_brace_space_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_c_s_s_1_1_class_definition_closing_brace_space_sniff" ]
];