var _class_instantiation_sniff_8php =
[
    [ "ClassInstantiationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_classes_1_1_class_instantiation_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_classes_1_1_class_instantiation_sniff" ]
];