var _closing_declaration_comment_unit_test_8php =
[
    [ "ClosingDeclarationCommentUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_commenting_1_1_closing_declaration_comment_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_commenting_1_1_closing_declaration_comment_unit_test" ]
];