var _comparison_method_does_not_declare_exactly_one_parameter_exception_8php =
[
    [ "ComparisonMethodDoesNotDeclareExactlyOneParameterException", "class_p_h_p_unit_1_1_framework_1_1_comparison_method_does_not_declare_exactly_one_parameter_exception.html", "class_p_h_p_unit_1_1_framework_1_1_comparison_method_does_not_declare_exactly_one_parameter_exception" ]
];