var _comparison_method_does_not_accept_parameter_type_exception_8php =
[
    [ "ComparisonMethodDoesNotAcceptParameterTypeException", "class_p_h_p_unit_1_1_framework_1_1_comparison_method_does_not_accept_parameter_type_exception.html", "class_p_h_p_unit_1_1_framework_1_1_comparison_method_does_not_accept_parameter_type_exception" ]
];