var _constant_visibility_sniff_8php =
[
    [ "ConstantVisibilitySniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_properties_1_1_constant_visibility_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_properties_1_1_constant_visibility_sniff" ]
];