var _concatenation_spacing_sniff_8php =
[
    [ "ConcatenationSpacingSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_strings_1_1_concatenation_spacing_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_strings_1_1_concatenation_spacing_sniff" ]
];