var _context_sensitive_keywords_test_8php =
[
    [ "ContextSensitiveKeywordsTest", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_context_sensitive_keywords_test.html", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_context_sensitive_keywords_test" ]
];