var _cyclomatic_complexity_sniff_8php =
[
    [ "CyclomaticComplexitySniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_metrics_1_1_cyclomatic_complexity_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_metrics_1_1_cyclomatic_complexity_sniff" ]
];