var _disallow_tab_indent_sniff_8php =
[
    [ "DisallowTabIndentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_white_space_1_1_disallow_tab_indent_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_white_space_1_1_disallow_tab_indent_sniff" ]
];