var _disallow_self_actions_unit_test_8php =
[
    [ "DisallowSelfActionsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_channels_1_1_disallow_self_actions_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_channels_1_1_disallow_self_actions_unit_test" ]
];