var _disallow_inline_if_sniff_8php =
[
    [ "DisallowInlineIfSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_p_h_p_1_1_disallow_inline_if_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_p_h_p_1_1_disallow_inline_if_sniff" ]
];