var _disallow_object_string_index_sniff_8php =
[
    [ "DisallowObjectStringIndexSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_objects_1_1_disallow_object_string_index_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_objects_1_1_disallow_object_string_index_sniff" ]
];