var _disallow_multiple_statements_sniff_8php =
[
    [ "DisallowMultipleStatementsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_disallow_multiple_statements_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_disallow_multiple_statements_sniff" ]
];