var _disallow_long_array_syntax_unit_test_8php =
[
    [ "DisallowLongArraySyntaxUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_arrays_1_1_disallow_long_array_syntax_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_arrays_1_1_disallow_long_array_syntax_unit_test" ]
];