var _disallow_yoda_conditions_unit_test_8php =
[
    [ "DisallowYodaConditionsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_control_structures_1_1_disallow_yoda_conditions_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_control_structures_1_1_disallow_yoda_conditions_unit_test" ]
];