var _disallow_new_widget_sniff_8php =
[
    [ "DisallowNewWidgetSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_objects_1_1_disallow_new_widget_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_objects_1_1_disallow_new_widget_sniff" ]
];