var _disallow_new_widget_unit_test_8php =
[
    [ "DisallowNewWidgetUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_objects_1_1_disallow_new_widget_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_objects_1_1_disallow_new_widget_unit_test" ]
];