var _disallow_self_actions_sniff_8php =
[
    [ "DisallowSelfActionsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_channels_1_1_disallow_self_actions_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_channels_1_1_disallow_self_actions_sniff" ]
];