var _doc_comment_alignment_sniff_8php =
[
    [ "DocCommentAlignmentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_commenting_1_1_doc_comment_alignment_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_commenting_1_1_doc_comment_alignment_sniff" ]
];