var _doc_comment_unit_test_8php =
[
    [ "DocCommentUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_commenting_1_1_doc_comment_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_commenting_1_1_doc_comment_unit_test" ]
];