var _duplicate_property_unit_test_8php =
[
    [ "DuplicatePropertyUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_classes_1_1_duplicate_property_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_classes_1_1_duplicate_property_unit_test" ]
];