var _duplicate_property_sniff_8php =
[
    [ "DuplicatePropertySniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_classes_1_1_duplicate_property_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_classes_1_1_duplicate_property_sniff" ]
];