var _echoed_strings_unit_test_8php =
[
    [ "EchoedStringsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_strings_1_1_echoed_strings_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_strings_1_1_echoed_strings_unit_test" ]
];