var _empty_statement_sniff_8php =
[
    [ "EmptyStatementSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_code_analysis_1_1_empty_statement_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_code_analysis_1_1_empty_statement_sniff" ]
];