var _end_file_no_newline_unit_test_8php =
[
    [ "EndFileNoNewlineUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_files_1_1_end_file_no_newline_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_files_1_1_end_file_no_newline_unit_test" ]
];