var _file_extension_unit_test_8php =
[
    [ "FileExtensionUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_files_1_1_file_extension_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_files_1_1_file_extension_unit_test" ]
];