var _firebug_console_unit_test_8php =
[
    [ "FirebugConsoleUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_debug_1_1_firebug_console_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_debug_1_1_firebug_console_unit_test" ]
];