var _function_comment_throw_tag_sniff_8php =
[
    [ "FunctionCommentThrowTagSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_commenting_1_1_function_comment_throw_tag_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_commenting_1_1_function_comment_throw_tag_sniff" ]
];