var _function_duplicate_argument_sniff_8php =
[
    [ "FunctionDuplicateArgumentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_function_duplicate_argument_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_function_duplicate_argument_sniff" ]
];