var _function_declaration_argument_spacing_sniff_8php =
[
    [ "FunctionDeclarationArgumentSpacingSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_function_declaration_argument_spacing_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_function_declaration_argument_spacing_sniff" ]
];