var _function_comment_throw_tag_unit_test_8php =
[
    [ "FunctionCommentThrowTagUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_commenting_1_1_function_comment_throw_tag_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_commenting_1_1_function_comment_throw_tag_unit_test" ]
];