var _function_declaration_argument_spacing_unit_test_8php =
[
    [ "FunctionDeclarationArgumentSpacingUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_functions_1_1_function_declaration_argument_spacing_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_functions_1_1_function_declaration_argument_spacing_unit_test" ]
];