var _function_opening_brace_space_sniff_8php =
[
    [ "FunctionOpeningBraceSpaceSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_function_opening_brace_space_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_function_opening_brace_space_sniff" ]
];