var _generic_2_sniffs_2_files_2_end_file_newline_sniff_8php =
[
    [ "EndFileNewlineSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_files_1_1_end_file_newline_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_files_1_1_end_file_newline_sniff" ]
];