var _generic_2_tests_2_white_space_2_scope_indent_unit_test_8php =
[
    [ "ScopeIndentUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_white_space_1_1_scope_indent_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_white_space_1_1_scope_indent_unit_test" ]
];