var _generic_2_sniffs_2_white_space_2_language_construct_spacing_sniff_8php =
[
    [ "LanguageConstructSpacingSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_white_space_1_1_language_construct_spacing_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_white_space_1_1_language_construct_spacing_sniff" ]
];