var _get_request_data_sniff_8php =
[
    [ "GetRequestDataSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_p_h_p_1_1_get_request_data_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_p_h_p_1_1_get_request_data_sniff" ]
];