var _git_merge_conflict_sniff_8php =
[
    [ "GitMergeConflictSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_version_control_1_1_git_merge_conflict_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_version_control_1_1_git_merge_conflict_sniff" ]
];