var _import_statement_sniff_8php =
[
    [ "ImportStatementSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_files_1_1_import_statement_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_files_1_1_import_statement_sniff" ]
];