var _include_own_system_sniff_8php =
[
    [ "IncludeOwnSystemSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_channels_1_1_include_own_system_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_sniffs_1_1_channels_1_1_include_own_system_sniff" ]
];