var _increment_decrement_usage_sniff_8php =
[
    [ "IncrementDecrementUsageSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_operators_1_1_increment_decrement_usage_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_operators_1_1_increment_decrement_usage_sniff" ]
];