var _inline_control_structure_sniff_8php =
[
    [ "InlineControlStructureSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_control_structures_1_1_inline_control_structure_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_control_structures_1_1_inline_control_structure_sniff" ]
];