var _inline_if_declaration_sniff_8php =
[
    [ "InlineIfDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_control_structures_1_1_inline_if_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_control_structures_1_1_inline_if_declaration_sniff" ]
];