var _interface_name_suffix_unit_test_8php =
[
    [ "InterfaceNameSuffixUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_naming_conventions_1_1_interface_name_suffix_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_naming_conventions_1_1_interface_name_suffix_unit_test" ]
];