var _interface_name_suffix_sniff_8php =
[
    [ "InterfaceNameSuffixSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_naming_conventions_1_1_interface_name_suffix_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_naming_conventions_1_1_interface_name_suffix_sniff" ]
];