var _join_strings_unit_test_8php =
[
    [ "JoinStringsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_strings_1_1_join_strings_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_my_source_1_1_tests_1_1_strings_1_1_join_strings_unit_test" ]
];