var _line_endings_unit_test_8php =
[
    [ "LineEndingsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_files_1_1_line_endings_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_files_1_1_line_endings_unit_test" ]
];