var _lowercase_class_keywords_sniff_8php =
[
    [ "LowercaseClassKeywordsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_classes_1_1_lowercase_class_keywords_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_classes_1_1_lowercase_class_keywords_sniff" ]
];