var _lowercase_function_keywords_sniff_8php =
[
    [ "LowercaseFunctionKeywordsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_lowercase_function_keywords_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_lowercase_function_keywords_sniff" ]
];