var _lowercase_class_keywords_unit_test_8php =
[
    [ "LowercaseClassKeywordsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_classes_1_1_lowercase_class_keywords_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_classes_1_1_lowercase_class_keywords_unit_test" ]
];