var _lowercase_declaration_unit_test_8php =
[
    [ "LowercaseDeclarationUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_control_structures_1_1_lowercase_declaration_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_control_structures_1_1_lowercase_declaration_unit_test" ]
];