var _lowercase_p_h_p_functions_sniff_8php =
[
    [ "LowercasePHPFunctionsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_p_h_p_1_1_lowercase_p_h_p_functions_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_p_h_p_1_1_lowercase_p_h_p_functions_sniff" ]
];