var _lowercase_function_keywords_unit_test_8php =
[
    [ "LowercaseFunctionKeywordsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_functions_1_1_lowercase_function_keywords_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_functions_1_1_lowercase_function_keywords_unit_test" ]
];