var _lowercase_p_h_p_functions_unit_test_8php =
[
    [ "LowercasePHPFunctionsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_p_h_p_1_1_lowercase_p_h_p_functions_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_p_h_p_1_1_lowercase_p_h_p_functions_unit_test" ]
];