var _matcher_already_registered_exception_8php =
[
    [ "MatcherAlreadyRegisteredException", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_matcher_already_registered_exception.html", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_matcher_already_registered_exception" ]
];