var _member_var_spacing_sniff_8php =
[
    [ "MemberVarSpacingSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_member_var_spacing_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_member_var_spacing_sniff" ]
];