var _method_name_not_configured_exception_8php =
[
    [ "MethodNameNotConfiguredException", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_method_name_not_configured_exception.html", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_method_name_not_configured_exception" ]
];