var _method_declaration_sniff_8php =
[
    [ "MethodDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_sniffs_1_1_methods_1_1_method_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_sniffs_1_1_methods_1_1_method_declaration_sniff" ]
];