var _method_parameters_already_configured_exception_8php =
[
    [ "MethodParametersAlreadyConfiguredException", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_method_parameters_already_configured_exception.html", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_method_parameters_already_configured_exception" ]
];