var _method_cannot_be_configured_exception_8php =
[
    [ "MethodCannotBeConfiguredException", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_method_cannot_be_configured_exception.html", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_method_cannot_be_configured_exception" ]
];