var _move_whitelist_excludes_to_coverage_8php =
[
    [ "MoveWhitelistExcludesToCoverage", "class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_move_whitelist_excludes_to_coverage.html", "class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_move_whitelist_excludes_to_coverage" ]
];