var _move_attributes_from_root_to_coverage_8php =
[
    [ "MoveAttributesFromRootToCoverage", "class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_move_attributes_from_root_to_coverage.html", "class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_move_attributes_from_root_to_coverage" ]
];