var _multi_line_function_declaration_unit_test_8php =
[
    [ "MultiLineFunctionDeclarationUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_functions_1_1_multi_line_function_declaration_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_functions_1_1_multi_line_function_declaration_unit_test" ]
];