var _multi_line_assignment_sniff_8php =
[
    [ "MultiLineAssignmentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_formatting_1_1_multi_line_assignment_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_formatting_1_1_multi_line_assignment_sniff" ]
];