var _multi_line_function_declaration_sniff_8php =
[
    [ "MultiLineFunctionDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_multi_line_function_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_functions_1_1_multi_line_function_declaration_sniff" ]
];