var _multi_line_condition_unit_test_8php =
[
    [ "MultiLineConditionUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_control_structures_1_1_multi_line_condition_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_control_structures_1_1_multi_line_condition_unit_test" ]
];