var _multiple_statement_alignment_sniff_8php =
[
    [ "MultipleStatementAlignmentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_multiple_statement_alignment_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_multiple_statement_alignment_sniff" ]
];