var _named_function_call_arguments_test_8php =
[
    [ "NamedFunctionCallArgumentsTest", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_named_function_call_arguments_test.html", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_named_function_call_arguments_test" ]
];