var _namespace_declaration_sniff_8php =
[
    [ "NamespaceDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_sniffs_1_1_namespaces_1_1_namespace_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_sniffs_1_1_namespaces_1_1_namespace_declaration_sniff" ]
];