var _no_space_after_cast_sniff_8php =
[
    [ "NoSpaceAfterCastSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_no_space_after_cast_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_no_space_after_cast_sniff" ]
];