var _no_space_after_cast_unit_test_8php =
[
    [ "NoSpaceAfterCastUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_formatting_1_1_no_space_after_cast_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_formatting_1_1_no_space_after_cast_unit_test" ]
];