var _non_executable_code_unit_test_8php =
[
    [ "NonExecutableCodeUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_p_h_p_1_1_non_executable_code_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_p_h_p_1_1_non_executable_code_unit_test" ]
];