var _non_executable_code_sniff_8php =
[
    [ "NonExecutableCodeSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_p_h_p_1_1_non_executable_code_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_p_h_p_1_1_non_executable_code_sniff" ]
];