var _object_operator_indent_sniff_8php =
[
    [ "ObjectOperatorIndentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_white_space_1_1_object_operator_indent_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_white_space_1_1_object_operator_indent_sniff" ]
];