var _one_object_structure_per_file_unit_test_8php =
[
    [ "OneObjectStructurePerFileUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_files_1_1_one_object_structure_per_file_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_files_1_1_one_object_structure_per_file_unit_test" ]
];