var _one_interface_per_file_sniff_8php =
[
    [ "OneInterfacePerFileSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_files_1_1_one_interface_per_file_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_files_1_1_one_interface_per_file_sniff" ]
];