var _opening_brace_space_unit_test_8php =
[
    [ "OpeningBraceSpaceUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_tests_1_1_classes_1_1_opening_brace_space_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_tests_1_1_classes_1_1_opening_brace_space_unit_test" ]
];