var _opening_function_brace_bsd_allman_sniff_8php =
[
    [ "OpeningFunctionBraceBsdAllmanSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_functions_1_1_opening_function_brace_bsd_allman_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_functions_1_1_opening_function_brace_bsd_allman_sniff" ]
];