var _opening_function_brace_bsd_allman_unit_test_8php =
[
    [ "OpeningFunctionBraceBsdAllmanUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_functions_1_1_opening_function_brace_bsd_allman_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_functions_1_1_opening_function_brace_bsd_allman_unit_test" ]
];