var _opening_brace_same_line_sniff_8php =
[
    [ "OpeningBraceSameLineSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_classes_1_1_opening_brace_same_line_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_classes_1_1_opening_brace_same_line_sniff" ]
];