var _opening_brace_same_line_unit_test_8php =
[
    [ "OpeningBraceSameLineUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_classes_1_1_opening_brace_same_line_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_classes_1_1_opening_brace_same_line_unit_test" ]
];