var _original_constructor_invocation_required_exception_8php =
[
    [ "OriginalConstructorInvocationRequiredException", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_original_constructor_invocation_required_exception.html", "class_p_h_p_unit_1_1_framework_1_1_mock_object_1_1_original_constructor_invocation_required_exception" ]
];