var _p_e_a_r_2_sniffs_2_naming_conventions_2_valid_class_name_sniff_8php =
[
    [ "ValidClassNameSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_naming_conventions_1_1_valid_class_name_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_naming_conventions_1_1_valid_class_name_sniff" ]
];