var _p_e_a_r_2_sniffs_2_commenting_2_inline_comment_sniff_8php =
[
    [ "InlineCommentSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_commenting_1_1_inline_comment_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_commenting_1_1_inline_comment_sniff" ]
];