var _p_e_a_r_2_tests_2_naming_conventions_2_valid_variable_name_unit_test_8php =
[
    [ "ValidVariableNameUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_naming_conventions_1_1_valid_variable_name_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_naming_conventions_1_1_valid_variable_name_unit_test" ]
];