var _p_e_a_r_2_sniffs_2_functions_2_function_call_signature_sniff_8php =
[
    [ "FunctionCallSignatureSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_functions_1_1_function_call_signature_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_functions_1_1_function_call_signature_sniff" ]
];