var _p_e_a_r_2_tests_2_commenting_2_class_comment_unit_test_8php =
[
    [ "ClassCommentUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_commenting_1_1_class_comment_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_commenting_1_1_class_comment_unit_test" ]
];