var _p_e_a_r_2_tests_2_classes_2_class_declaration_unit_test_8php =
[
    [ "ClassDeclarationUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_classes_1_1_class_declaration_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_tests_1_1_classes_1_1_class_declaration_unit_test" ]
];