var _p_e_a_r_2_sniffs_2_white_space_2_scope_closing_brace_sniff_8php =
[
    [ "ScopeClosingBraceSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_white_space_1_1_scope_closing_brace_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_white_space_1_1_scope_closing_brace_sniff" ]
];