var _p_s_r2_2_tests_2_namespaces_2_use_declaration_unit_test_8php =
[
    [ "UseDeclarationUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_tests_1_1_namespaces_1_1_use_declaration_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_tests_1_1_namespaces_1_1_use_declaration_unit_test" ]
];