var _p_s_r12_2_sniffs_2_traits_2_use_declaration_sniff_8php =
[
    [ "UseDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_traits_1_1_use_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_traits_1_1_use_declaration_sniff" ]
];