var _p_s_r2_2_sniffs_2_files_2_closing_tag_sniff_8php =
[
    [ "ClosingTagSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_sniffs_1_1_files_1_1_closing_tag_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_sniffs_1_1_files_1_1_closing_tag_sniff" ]
];