var _p_s_r12_2_tests_2_operators_2_operator_spacing_unit_test_8php =
[
    [ "OperatorSpacingUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_tests_1_1_operators_1_1_operator_spacing_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_tests_1_1_operators_1_1_operator_spacing_unit_test" ]
];