var _p_s_r2_2_tests_2_control_structures_2_else_if_declaration_unit_test_8php =
[
    [ "ElseIfDeclarationUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_tests_1_1_control_structures_1_1_else_if_declaration_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_tests_1_1_control_structures_1_1_else_if_declaration_unit_test" ]
];