var _p_s_r12_2_sniffs_2_operators_2_operator_spacing_sniff_8php =
[
    [ "OperatorSpacingSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_operators_1_1_operator_spacing_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_operators_1_1_operator_spacing_sniff" ]
];