var _p_s_r2_2_tests_2_files_2_end_file_newline_unit_test_8php =
[
    [ "EndFileNewlineUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_tests_1_1_files_1_1_end_file_newline_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r2_1_1_tests_1_1_files_1_1_end_file_newline_unit_test" ]
];