var _prophesize_dynamic_return_type_extension_8php =
[
    [ "ProphesizeDynamicReturnTypeExtension", "class_jan_gregor_1_1_prophecy_1_1_type_1_1_prophet_1_1_prophesize_dynamic_return_type_extension.html", "class_jan_gregor_1_1_prophecy_1_1_type_1_1_prophet_1_1_prophesize_dynamic_return_type_extension" ]
];