var _require_strict_types_sniff_8php =
[
    [ "RequireStrictTypesSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_p_h_p_1_1_require_strict_types_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_p_h_p_1_1_require_strict_types_sniff" ]
];