var _return_type_declaration_sniff_8php =
[
    [ "ReturnTypeDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_functions_1_1_return_type_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_functions_1_1_return_type_declaration_sniff" ]
];