var _rule_inclusion_absolute_linux_test_8php =
[
    [ "RuleInclusionAbsoluteLinuxTest", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_ruleset_1_1_rule_inclusion_absolute_linux_test.html", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_ruleset_1_1_rule_inclusion_absolute_linux_test" ]
];