var _short_form_type_keywords_sniff_8php =
[
    [ "ShortFormTypeKeywordsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_keywords_1_1_short_form_type_keywords_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_s_r12_1_1_sniffs_1_1_keywords_1_1_short_form_type_keywords_sniff" ]
];