var _space_before_cast_sniff_8php =
[
    [ "SpaceBeforeCastSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_space_before_cast_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_space_before_cast_sniff" ]
];