var _space_after_not_unit_test_8php =
[
    [ "SpaceAfterNotUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_formatting_1_1_space_after_not_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_formatting_1_1_space_after_not_unit_test" ]
];