var _space_after_not_sniff_8php =
[
    [ "SpaceAfterNotSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_space_after_not_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_formatting_1_1_space_after_not_sniff" ]
];