var _spread_operator_spacing_after_sniff_8php =
[
    [ "SpreadOperatorSpacingAfterSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_white_space_1_1_spread_operator_spacing_after_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_white_space_1_1_spread_operator_spacing_after_sniff" ]
];