var _squiz_2_sniffs_2_control_structures_2_else_if_declaration_sniff_8php =
[
    [ "ElseIfDeclarationSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_control_structures_1_1_else_if_declaration_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_control_structures_1_1_else_if_declaration_sniff" ]
];