var _squiz_2_tests_2_naming_conventions_2_valid_function_name_unit_test_8php =
[
    [ "ValidFunctionNameUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_naming_conventions_1_1_valid_function_name_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_naming_conventions_1_1_valid_function_name_unit_test" ]
];