var _squiz_2_tests_2_commenting_2_inline_comment_unit_test_8php =
[
    [ "InlineCommentUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_commenting_1_1_inline_comment_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_commenting_1_1_inline_comment_unit_test" ]
];