var _squiz_2_sniffs_2_control_structures_2_control_signature_sniff_8php =
[
    [ "ControlSignatureSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_control_structures_1_1_control_signature_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_control_structures_1_1_control_signature_sniff" ]
];