var _squiz_2_tests_2_white_space_2_language_construct_spacing_unit_test_8php =
[
    [ "LanguageConstructSpacingUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_white_space_1_1_language_construct_spacing_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_white_space_1_1_language_construct_spacing_unit_test" ]
];