var _squiz_2_sniffs_2_white_space_2_control_structure_spacing_sniff_8php =
[
    [ "ControlStructureSpacingSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_control_structure_spacing_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_control_structure_spacing_sniff" ]
];