var _stable_comment_whitespace_test_8php =
[
    [ "StableCommentWhitespaceTest", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_stable_comment_whitespace_test.html", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_stable_comment_whitespace_test" ]
];