var _static_this_usage_sniff_8php =
[
    [ "StaticThisUsageSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_scope_1_1_static_this_usage_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_scope_1_1_static_this_usage_sniff" ]
];