var _subversion_properties_unit_test_8php =
[
    [ "SubversionPropertiesUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_version_control_1_1_subversion_properties_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_version_control_1_1_subversion_properties_unit_test" ]
];