var _subversion_properties_sniff_8php =
[
    [ "SubversionPropertiesSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_version_control_1_1_subversion_properties_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_version_control_1_1_subversion_properties_sniff" ]
];