var _superfluous_whitespace_sniff_8php =
[
    [ "SuperfluousWhitespaceSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_superfluous_whitespace_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_white_space_1_1_superfluous_whitespace_sniff" ]
];