var _superfluous_whitespace_unit_test_8php =
[
    [ "SuperfluousWhitespaceUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_white_space_1_1_superfluous_whitespace_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_white_space_1_1_superfluous_whitespace_unit_test" ]
];