var _unconditional_if_statement_unit_test_8php =
[
    [ "UnconditionalIfStatementUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_code_analysis_1_1_unconditional_if_statement_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_code_analysis_1_1_unconditional_if_statement_unit_test" ]
];