var _undo_namespaced_name_single_token_test_8php =
[
    [ "UndoNamespacedNameSingleTokenTest", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_undo_namespaced_name_single_token_test.html", "class_p_h_p___code_sniffer_1_1_tests_1_1_core_1_1_tokenizer_1_1_undo_namespaced_name_single_token_test" ]
];