var _unintentionally_covered_code_exception_8php =
[
    [ "UnintentionallyCoveredCodeException", "class_sebastian_bergmann_1_1_code_coverage_1_1_unintentionally_covered_code_exception.html", "class_sebastian_bergmann_1_1_code_coverage_1_1_unintentionally_covered_code_exception" ]
];