var _unnecessary_string_concat_sniff_8php =
[
    [ "UnnecessaryStringConcatSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_strings_1_1_unnecessary_string_concat_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_strings_1_1_unnecessary_string_concat_sniff" ]
];