var _unnecessary_final_modifier_sniff_8php =
[
    [ "UnnecessaryFinalModifierSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_code_analysis_1_1_unnecessary_final_modifier_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_code_analysis_1_1_unnecessary_final_modifier_sniff" ]
];