var _upper_case_constant_sniff_8php =
[
    [ "UpperCaseConstantSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_p_h_p_1_1_upper_case_constant_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_sniffs_1_1_p_h_p_1_1_upper_case_constant_sniff" ]
];