var _upper_case_constant_unit_test_8php =
[
    [ "UpperCaseConstantUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_p_h_p_1_1_upper_case_constant_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_generic_1_1_tests_1_1_p_h_p_1_1_upper_case_constant_unit_test" ]
];