var _valid_logical_operators_sniff_8php =
[
    [ "ValidLogicalOperatorsSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_operators_1_1_valid_logical_operators_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_sniffs_1_1_operators_1_1_valid_logical_operators_sniff" ]
];