var _valid_logical_operators_unit_test_8php =
[
    [ "ValidLogicalOperatorsUnitTest", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_operators_1_1_valid_logical_operators_unit_test.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_squiz_1_1_tests_1_1_operators_1_1_valid_logical_operators_unit_test" ]
];