var _valid_default_value_sniff_8php =
[
    [ "ValidDefaultValueSniff", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_functions_1_1_valid_default_value_sniff.html", "class_p_h_p___code_sniffer_1_1_standards_1_1_p_e_a_r_1_1_sniffs_1_1_functions_1_1_valid_default_value_sniff" ]
];