var _will_extend_or_implement_dynamic_return_type_extension_8php =
[
    [ "WillExtendOrImplementDynamicReturnTypeExtension", "class_jan_gregor_1_1_prophecy_1_1_type_1_1_object_prophecy_1_1_will_extend_or_implement_dynamic_return_type_extension.html", "class_jan_gregor_1_1_prophecy_1_1_type_1_1_object_prophecy_1_1_will_extend_or_implement_dynamic_return_type_extension" ]
];